import Link from "next/link";
import { Shield, FileText, Scale, CheckCircle } from "lucide-react";

export default function GovernanceContractPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header Minimalista */}
      <header className="border-b border-gray-100 bg-white sticky top-0 z-10">
        <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-green-600 text-white">
              <Shield size={18} />
            </div>
            <span className="text-xl font-black text-gray-900 tracking-tight">EcoLink.</span>
          </Link>
          <div className="text-sm font-semibold text-gray-500">Governance & Compliance Framework</div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-12">
          <h1 className="text-4xl font-black text-gray-900 mb-4 tracking-tight">
            Australian Governance & Service Agreement
          </h1>
          <p className="text-lg text-gray-600">
            This document outlines how EcoLink Australia automated carbon accounting services comply with Australian federal and state legislation.
          </p>
          <div className="mt-6 flex items-center gap-2 text-sm font-medium text-green-700 bg-green-50 w-fit px-4 py-2 rounded-full border border-green-200">
            <CheckCircle size={16} /> Fully aligned with AASB S2 and NGA 2023-24 Guidelines
          </div>
        </div>

        <div className="prose prose-gray max-w-none">
          <section className="mb-10">
            <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 border-b pb-2">
              <Scale className="text-blue-600" /> 1. Regulatory Framework & Standards
            </h2>
            <p className="mt-4 text-gray-700 leading-relaxed">
              EcoLink Australia provides automated greenhouse gas (GHG) emissions calculations and sustainability reporting tools for Australian Small and Medium Enterprises (SMEs). All data processing, emission factors, and reporting formats are strictly governed by the following Australian frameworks:
            </p>
            <ul className="mt-4 space-y-2 text-gray-700">
              <li><strong>National Greenhouse and Energy Reporting (NGER) Act 2007:</strong> Underpins the foundational methodologies for Scope 1 and Scope 2 emissions calculations.</li>
              <li><strong>National Greenhouse Accounts (NGA) Factors:</strong> The platform explicitly utilizes the latest emission factors published by the Department of Climate Change, Energy, the Environment and Water (DCCEEW) for the 2023-24 period.</li>
              <li><strong>AASB S1 and AASB S2:</strong> Reports generated by the platform are formatted to comply with the Australian Accounting Standards Board's climate-related financial disclosure requirements, aligned with the IFRS Foundation standards.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 border-b pb-2">
              <Shield className="text-blue-600" /> 2. Data Sovereignty & Privacy Act 1988
            </h2>
            <p className="mt-4 text-gray-700 leading-relaxed">
              As a provider of financial and operational data analysis, EcoLink Australia is committed to the highest standards of data security governed by Australian law.
            </p>
            <ul className="mt-4 space-y-2 text-gray-700">
              <li><strong>Australian Privacy Principles (APPs):</strong> We adhere to the 13 APPs contained in Schedule 1 of the Privacy Act 1988 (Cth). Data collected via our API, Xero, or manual uploads is used exclusively for the purpose of carbon accounting.</li>
              <li><strong>Data Hosting:</strong> All primary databases and backup systems storing Australian user data are hosted in onshore data centres (Sydney, AWS/Railway region ap-southeast-2) to ensure data sovereignty.</li>
              <li><strong>Encryption:</strong> Financial data and OAuth tokens (e.g., Xero connections) are encrypted at rest using AES-256 and in transit via TLS 1.3.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 border-b pb-2">
              <FileText className="text-blue-600" /> 3. Business Identity & ABN Verification
            </h2>
            <p className="mt-4 text-gray-700 leading-relaxed">
              To prevent fraudulent reporting and ensure the integrity of the carbon tracking ecosystem:
            </p>
            <ul className="mt-4 space-y-2 text-gray-700">
              <li><strong>ABN Mod-89 Algorithm:</strong> Every company registering on EcoLink must provide an 11-digit Australian Business Number. Our systems perform a cryptographic checksum validation (Mod-89) against the Australian Business Register (ABR) algorithm before provisioning an account.</li>
              <li><strong>Tax Invoices:</strong> All subscriptions processed via Stripe include a compliant Australian Tax Invoice displaying a 10% Goods and Services Tax (GST) as required by the ATO under the A New Tax System (Goods and Services Tax) Act 1999.</li>
            </ul>
          </section>

          <section className="mb-10 p-6 bg-gray-50 rounded-2xl border border-gray-200">
            <h3 className="text-lg font-bold text-gray-900 mb-2">Service Level Agreement (SLA) & Liability</h3>
            <p className="text-sm text-gray-600 leading-relaxed">
              While EcoLink’s AI Swarm agents automate the ingestion and calculation of scope emissions, the ultimate responsibility for data accuracy submitted to regulatory bodies rests with the registered business entity. EcoLink acts as a facilitator and data processing software, not as a certified environmental auditor. For audited submissions, we recommend having EcoLink reports reviewed by a registered NGER auditor.
            </p>
          </section>
        </div>
        
        <div className="mt-12 pt-8 border-t border-gray-200 text-sm text-gray-500 flex justify-between items-center">
          <span>Last Updated: April 2026</span>
          <span>© EcoLink Australia</span>
        </div>
      </main>
    </div>
  );
}
